name-template: '<build num>-$GITHUB_SHA - <DD Month YYYY>'
tag-template: '<build num>-$GITHUB_SHA'
replacers:
  - search: '/DRT-(\d+)/g'
    replace: '[$1](https://github.com/pads/draft-release-test/issues/$1)'
categories:
  - title: 'Features'
    label: '[feature]'
  - title: 'Bug Fixes'
    label: '[fix]'      
template: |
  ## What’s Changed

  $CHANGES
