_extends: .github
name-template: v1 🌈
replacers:
  - search: '/DRT-(\d+)/g'
    replace: '[DRT-$1](https://github.com/pads/draft-release-test/issues/$1)'
categories:
  - title: 'Features'
    label: 'feature'
  - title: 'Bug Fixes'
    label: 'bug'      
template: |
  ## What’s Changed

  $CHANGES
