name-template: 'BUILDNUM-$GITHUB_SHA - DD Month YYYY'
tag-template: 'BUILDNUM-$GITHUB_SHA'
replacers:
  - search: '/DRT-(\d+)/g'
    replace: '[DRT-$1](https://github.com/pads/draft-release-test/issues/$1)'
categories:
  - title: 'Features'
    label: 'feature'
  - title: 'Bug Fixes'
    label: 'bug'      
template: |
  ## What’s Changed

  $CHANGES
